### ISSUE TITLE
Proposal: Don't show date format in range header text if no date is selected

### ISSUE THREAD

**Issue by kfirba** [mathieustan/vue-datepicker#11]
Hey!

Currently, the header text is showing something like `From DD MM YYYY` and `To DD MM YYYY` as the placeholder when there is no date selected, which is kind of weird in my opinion. Users are usually not aware of date formats and it does not give them any real benefit.

I propose 2 solutions:

1. Don't show the placeholder at all. Just like you'd done in the "single date" mode, show a `-` before the user chooses a date.
2. Just show the `From` and `To` texts without the date format.

Personally, I lean toward the second option as it gives the user some indication that this is a range picker and we are "waiting" for his input, opposed to the `-` solution where it's not immediately clear what it stands for.

The change should be rather easy, for the second solution:

```js
export function getRangeDatesFormatted ({ start, end } = {}, { lang }, format) {
  const locale = getLocale(lang);

  if (!start && !end) {
    return ` ~ `;
  }

  if (!start && end) {
    return ` ~ ${dayjs(end).locale(locale).startOf('day').format(format)}`;
  }

  if (start && !end) {
    return `${dayjs(start).locale(locale).startOf('day').format(format)} ~ `;
  }

  return `\
${dayjs(start).locale(locale).startOf('day').format(format)} \
~ \
${dayjs(end).locale(locale).startOf('day').format(format)}`;
}
```

**Comment by mathieustan** [comment]
Done in V0.1.8
