### ISSUE TITLE
Bug: selecting dates in range mode bug

### ISSUE THREAD

**Issue by kfirba** [mathieustan/vue-datepicker#12]
There is a bug with `fullscreen-mobile` mode and the range datepicker where I can get the following state:

![image](https://user-images.githubusercontent.com/8510486/64695484-ef897980-d4a4-11e9-8a65-f7d6f6b13799.png)

As you can see, I've chosen a range but the range itself was not properly selected.

How to reproduce:

1. Open the datepicker in `range` mode and `fullscreen-mobile`**on mobile device**
2. Pick a start date, for example, September 3rd.
3. Pick an end date, for example, September 19th.
4. Click on September 19th again
5. Now pick another date in the past, for example, September 11th.

Try it a few times. It happens every so often. There is no console error.

In the Vue devtools the `end` date is really **before** the `start` date.

I guess the easiest way to fix this is to add a watcher that ensures that the `start` date is always **before** the `end` date and swap them if it's not the case.

**Comment by mathieustan** [comment]
I'll check this. Thanks

**Comment by mathieustan** [comment]
Done in V0.1.8
