### ISSUE TITLE
Bug: Passing `null` in range-mode causes errors

### ISSUE THREAD

**Issue by kfirba** [mathieustan/vue-datepicker#14]
It's me again,

Passing `null` as start/end values in range-mode (maybe even in single mode, haven't tested) causes errors.

```js
data() {
      return {
        dates: {
          start: null,
          end: null,
        },
      };
    },
```

![image](https://user-images.githubusercontent.com/8510486/65221306-70f49380-dac5-11e9-9dc8-33e1d723e873.png)

Surprisingly enough, changing the values to `undefined` solves the problem. I think this is a bug and `null` should be treated like `undefined`.

```js
data() {
      return {
        dates: {
          start: undefined, // null should also be accepted?
          end: undefined, // // null should also be accepted?
        },
      };
    },
```

**Comment by mathieustan** [comment]
Hello there, 

Apparently, it seems like dayjs treat null as an invalid date. 

There is two way to init date range : 

```
dates: undefined 
```

or 

```
dates: { start: undefined, end: undefined }
```

**Comment by kfirba** [comment]
@mathieustan Alright. What if we turn `null` to `undefined` in the component itself instead of passing the raw value to dayjs? Are there any downsides to transforming `null` to `undefined` just before we pass the values to dayjs or when we accept the prop?

**Comment by mathieustan** [comment]
Closed. Done in [v0.2.0](https://github.com/mathieustan/vue-datepicker/releases/tag/0.2.0)
