### ISSUE TITLE
box-sizing:border-box

### ISSUE THREAD

**Issue by Janoski** [mathieustan/vue-datepicker#17]
Hi !

Your lib is cool. But you're adding a global CSS property :
*,::after,::before{box-sizing:border-box}

Is that possible to remove this or just apply this on the component only.

**Comment by mathieustan** [comment]
Hello @Janoski,

There are two files where I applied borderbox: 

https://github.com/mathieustan/vue-datepicker/blob/b22145fc9cc4cbae0284d28e2d0f47adcc120356/src/components/datepicker/DatePicker.vue#L247

https://github.com/mathieustan/vue-datepicker/blob/b22145fc9cc4cbae0284d28e2d0f47adcc120356/src/components/datepicker/DatePickerAgenda.vue#L531

both are applied to component and child only.
