### ISSUE TITLE
Error handling french dates

### ISSUE THREAD

**Issue by ntoniazzi** [mathieustan/vue-datepicker#18]
There seems to be a typo here:
https://github.com/mathieustan/vue-datepicker/blob/master/src/components/datepicker/DatePicker.vue#L174
outPutFormat is never defined (capital P)

If I set the locale to "fr" and the format to "DD/MM/YYYY", the calendar chokes on invalid english dates such as: "28/02/2019"

**Comment by mathieustan** [comment]
Hello @ntoniazzi,

Are you using `formatOutput` prop ? I'll remove it to avoid this issue.

**Comment by mathieustan** [comment]
`formatOutput` prop has been removed. 
You should not have this issue anymore. 

Let me know if it still happens.
