### ISSUE TITLE
DatePicker in range mode shows a console error

### ISSUE THREAD

**Issue by bissolli** [mathieustan/vue-datepicker#19]
Hey guys,

Just found an error very similar to the #13, which I could also reproduce on the demo site:

```
TypeError: Cannot read property 'start' of undefined
    at a.rangeCurrentHoveredDay (vue-datepicker.esm.js:3771)
    at nr.run (vue.runtime.esm.js:4562)
    at qn (vue.runtime.esm.js:4304)
    at Array.<anonymous> (vue.runtime.esm.js:1980)
    at ue (vue.runtime.esm.js:1906)
```

The error does not affect the functionality as the datepicker still works, but it throws few errors in the console.

To reproduce on the demo site, just keep changing the selection and it will suddenly appears.

![image](https://user-images.githubusercontent.com/1808444/65829604-2c80a900-e2b8-11e9-9157-5abd5bb536a4.png)

**Comment by DmitriyBesedin** [comment]
Hello. This does not just write an error to the console, this error completely breaks the  NUXT page.

**Comment by mathieustan** [comment]
Ok. I'll fix that

**Comment by mathieustan** [comment]
Closed. Done in [v0.2.0](https://github.com/mathieustan/vue-datepicker/releases/tag/0.2.0)
