### ISSUE TITLE
Change formatting of date range presentation

### ISSUE THREAD

**Issue by Olkyore** [mathieustan/vue-datepicker#2]
Hi,

I want use your library but i need to change the presentation of your result presentation like : 
2019/07/22 ~ 2019/07/25 by Du 2019/07/22 au 2019/07/25

The only way i found was to modify your file Dates.js, function getRangeDatesFormatted (replace ~by "Du" and "au", and DatePickerHeader.vue, function dateFormatted to replace split "~" by "au" and apply a new split to remove "du".

I haven't see a param to do that, can i use the version with my modification with fix version ? Or maybe you should interested for a pull Request with this new param to modify the presentation of rangeDatesFormatted 

Cordially,

**Comment by mathieustan** [comment]
Hello @Olkyore, I think it's a good idea. I'll implement this soon.

**Comment by mathieustan** [comment]
Added a property to customize input. 
[#0.1.8.rc.3](https://github.com/mathieustan/vue-datepicker/releases/tag/0.1.8.rc.3)
