### ISSUE TITLE
Adding Github link in the documentation

### ISSUE THREAD

**Issue by guillaumebriday** [mathieustan/vue-datepicker#22]
The documentation is 👌.

But it's could be great to add a link to this repo.

Thank you

**Comment by mathieustan** [comment]
Good idea 👍

**Comment by mathieustan** [comment]
Closed. Done in [v0.2.0](https://github.com/mathieustan/vue-datepicker/releases/tag/0.2.0)

**Comment by guillaumebriday** [comment]
Nice 🎉
