### ISSUE TITLE
Was the import VueDatePicker locally removed on v0.2.0?

### ISSUE THREAD

**Issue by bissolli** [mathieustan/vue-datepicker#30]
Tried updating to `v0.2.0` and looks like the option to import VueDatePicker locally in the component was removed.

Was that on purpose?

**Error**
> export 'VueDatePicker' was not found in '@mathieustan/vue-datepicker

**Code example**
```javascript
import { VueDatePicker } from "@mathieustan/vue-datepicker";

export default {
  name: "DatePickerRange",
  components: {
    VueDatePicker
  }
  ...
```

**Comment by kfirba** [comment]
I can confirm the bug exists. I also can't import the component locally anymore.

**Comment by mathieustan** [comment]
Hello, 

No it wasn't on purpose 😞. My bad. I'll change that

**Comment by kfirba** [comment]
@mathieustan Thanks!

Is this a patch release that will be released soon?

**Comment by mathieustan** [comment]
@kfirba && @bissolli Should be fixed on latest release.
