### ISSUE TITLE
SSR issue

### ISSUE THREAD

**Issue by fabeat** [mathieustan/vue-datepicker#31]
After upgrading to the newest version of the DatePicker, i get the following error while building the application:
` ReferenceError: window is not defined` in `/get-size/get-size.js:23:1`

The problem seems to be, that `get-size` requires `window` as soon as it is imported.

This means that wrapping the datepicker in `<ClientOnly>` does not solve this issue.

**Comment by fabeat** [comment]
I found a workaround (importing the component in the `mounted` lifecycle hook):

In your component:
```javascript
data() {
  return {
    date: undefined,
    datepickerComponent: undefined
  };
},
mounted () {
  import('@mathieustan/vue-datepicker').then(module => {
    this.datepickerComponent = module.VueDatePicker
  })
}
```

In your template:
```vue
<component
  v-if="datepickerComponent"
  :is="datepickerComponent"
  v-model="date"
  ...
/>
```

**Comment by mathieustan** [comment]
Hello @fabeat,

indeed, it is not normal to have to import it in mounted hook. I'm going to look at this to make it ssr compatible.

**Comment by mathieustan** [comment]
@fabeat It should work now. Let me know.
