### ISSUE TITLE
Proposal : Adding slot or date callback and disable CSS

### ISSUE THREAD

**Issue by Mushr0000m** [mathieustan/vue-datepicker#32]
Hi, your component looks very good 👍  and I would like to use but I need to add some code on dates, like a dot or a count of events on this date. I think a slot scope for dates creation or a callback that return the html for the date would be very nice.

Also could you consider to have an option to disable style so we can use our without having to overide a lot of rules.

Thanks

**Comment by mathieustan** [comment]
Hello @Mushr0000m.

You could use a custom activator with a filter on date. 

```html
<VueDatePicker v-model="date" >
  <template #activator="{ date }">
    <button
      ref="activator"
      type="button"
    >
      {{ date | yourCustomFilter }}
    </button>
  </template>
</VueDatePicker>
```

I'll check to add more configuration on style

**Comment by mathieustan** [comment]
Since v0.2.5, you can use a Custom day slot. 

Check an example [here](https://vue-datepicker.netlify.app/). => # Custom day slot
