### ISSUE TITLE
Proposal: reset button or slot for buttons

### ISSUE THREAD

**Issue by carestad** [mathieustan/vue-datepicker#33]
Love the component! I am currently just implementing my own reset button outside of the component itself, but I would love it if there was a way to reset the currently selected date or date range within the date picker itself.

Either enable this with a prop, or maybe allow to append or control the action buttons (`OK`/`Cancel` when `:validate` is `true`) via slots.

**Comment by mathieustan** [comment]
Clearable prop which allows to clean input in [lastest version](https://github.com/mathieustan/vue-datepicker/releases/tag/0.2.3-rc.2)
