### ISSUE TITLE
Datepicker model should be retain the date type

### ISSUE THREAD

**Issue by mkhanal** [mathieustan/vue-datepicker#35]
Right now the v-model can take a string or a date type. 

Consider the following scenario
```
aDate = new Date() // a date type object
```
and
```
<vue-datepicker v-model="aDate"/>
```

When `aDate` gets updated by the datepicker, it is converted to a String type instead of date. The component should retain its type.

**Comment by mathieustan** [comment]
Hello @mkhanal,

I prefer to return a string because it is easier to format it afterwards.
Easier to use with `new Date`, `time`, `datejs` or simply as a string.

What do you think ?

**Comment by mathieustan** [comment]
Close for now. :)
