### ISSUE TITLE
Allow unsetting the input text-colour

### ISSUE THREAD

**Issue by AAllport** [mathieustan/vue-datepicker#38]
Lemmie start off by saying, I'm so glad I've discovered this package, great job!

However, have you got any guidance for putting different styling in for the text and the header.
For context, the blue looks great for the header of the dropdown, but, once the user has selected the date, the input box contains blue text, as opposed to the page's default.

Is there currently an easy way to have the default input styling once the dropdown is closed.

Failing that, please can I propose adding a `text-color` prop that can either be a string or "false", where false would just not add the colour style attribute to the input box?

Thanks!

**Comment by mathieustan** [comment]
Hello @AAllport,

You're totally right. I really don't remenber why I put this blue color when date has been setted. 
I'm not in favor to add a new props to update this color. 

I think, i'll create a them props which allow to define custom style when we init the datepicker.

**Comment by mathieustan** [comment]
@AAllport should be done. 

=> [Release](https://github.com/mathieustan/vue-datepicker/releases/tag/0.2.3-rc.2)

**Comment by AAllport** [comment]
Nice one!
