### ISSUE TITLE
Is it possible to disable some days in a week

### ISSUE THREAD

**Issue by kelanik8** [mathieustan/vue-datepicker#44]

**Comment by mathieustan** [comment]
Hello @kelanik8,

A new prop allowedDates will be available in next release.

**Comment by kelanik8** [comment]
Hello @mathieustan 
Thanks for this package. The User experience is really Awesome.

I am not sure! also, is it possible to disable past days and disable the days like this format 
['mon', 'tue', 'sun']

**Comment by mathieustan** [comment]
> Hello @mathieustan
> Thanks for this package. The User experience is really Awesome.
> 
> I am not sure! also, is it possible to disable past days and disable the days like this format
> ['mon', 'tue', 'sun']

Yes you can. I added an example in page for new prop : allowedDates

Done in [v0.2.3](https://github.com/mathieustan/vue-datepicker/releases/tag/0.2.3)

**Comment by iKlsR** [comment]
This is broken since 0.2.9 or so, the date is a string and not a date object.

**Comment by mathieustan** [comment]
@iKlsR yeah it changes. Date is a string. Check out example in doc.
