### ISSUE TITLE
Bundle Size

### ISSUE THREAD

**Issue by Kunoacc** [mathieustan/vue-datepicker#45]
When building from vue ui, the size of the bundle is actually large at 140KB. It's the largest dependency in my project. Is there any way to shrink this?

![image](https://user-images.githubusercontent.com/16244990/82692154-1795c300-9c57-11ea-9a68-68ead72430cb.png)

**Comment by mathieustan** [comment]
Thanks @Kunoacc. 

I'll look at it, and try to improve this asap

**Comment by mathieustan** [comment]
It seems like css in vue components take alot of space. I’ll extract style in a css minified file.

**Comment by Kunoacc** [comment]
Awesome!

Thanks @mathieustan 

Any way to be able to pick what date library to use?

i see you're using dayjs and in our project we use moment. It'll be an extra unnecessary dependency that we wouldn't end up using. Probably a way to specify a default?

**Comment by mathieustan** [comment]
I will delete dayjs one day to use only javascript dates. But for the moment, in fact, you will have 2 libs to manage the date. 

Maybe you should use dayjs instead of time which is much heavier :)

By the way dayjs is really thin.

**Comment by mathieustan** [comment]
## Previous release v0.2.3-rc.2 : 
![Capture d’écran 2020-05-26 à 12 49 04](https://user-images.githubusercontent.com/38033090/82892370-9fc5e200-9f4f-11ea-8623-ed4c0972090d.png)

## [Latest release v0.2.3](https://github.com/mathieustan/vue-datepicker/releases/tag/0.2.3)
![Capture d’écran 2020-05-26 à 12 49 22](https://user-images.githubusercontent.com/38033090/82892374-a05e7880-9f4f-11ea-9404-58c22b39f91d.png)

I'll close for the moment. Let me know.
