### ISSUE TITLE
After updating i get "TypeError: Cannot read property 'symbol' of undefined"

### ISSUE THREAD

**Issue by Kunoacc** [mathieustan/vue-datepicker#46]
After the last publish update, when i updated and reran the project, i got this "TypeError: Cannot read property 'symbol' of undefined".

Are they any breaking changes?

**Comment by mathieustan** [comment]
Weird. There is no error on demo page. 
Did you try to remove and install package again ? 
Do you have more info to help me ?

**Comment by mathieustan** [comment]
@Kunoacc Do you still have this issue ? Can you send me a reproduction link ?

**Comment by mathieustan** [comment]
I close this issue. If you still have an issue, let me know.
