### ISSUE TITLE
After install v0.2.3 the dist folder does not have the CSS.

### ISSUE THREAD

**Issue by DanielAlcaraz** [mathieustan/vue-datepicker#48]
Can't find:
`import '@mathieustan/vue-datepicker/dist/vue-datepicker.min.css';`

In the `dist` folder there is only the vue-datepicker.esm.js, vue-datepicker.min.js and vue-datepicker.umd.js

**Comment by KristenLeach** [comment]
Having this trouble as well, I believe. Calendar is showing up as image shows; above the uppermost header of our webpage. Tried importing CSS stylesheet separately in vue-config, but that is not working. Any help would be appreciated. 

![Screen Shot 2020-06-02 at 3 10 50 PM](https://user-images.githubusercontent.com/31492991/83574956-5e9b7800-a4e3-11ea-99ef-e5f88117a7b8.png)

**Comment by DanielAlcaraz** [comment]
> 
> 
> Having this issue as well, I believe. Calendar is showing up as the attached image shows; above the uppermost header of our webpage. Tried importing the provided CSS stylesheet separately in vue-config, but that is not working. Any help would be appreciated.
> 
> Edited to add: locking at 0.2.2 works for the time being.
> 
> ![Screen Shot 2020-06-02 at 3 10 50 PM](https://user-images.githubusercontent.com/31492991/83574956-5e9b7800-a4e3-11ea-99ef-e5f88117a7b8.png)

Same result.

**Comment by mednikoviurii** [comment]
> 
> 
> Having this issue as well, I believe. Calendar is showing up as the attached image shows; above the uppermost header of our webpage. Tried importing the provided CSS stylesheet separately in vue-config, but that is not working. Any help would be appreciated.
> 
> Edited to add: locking at 0.2.2 works for the time being.
> 
> ![Screen Shot 2020-06-02 at 3 10 50 PM](https://user-images.githubusercontent.com/31492991/83574956-5e9b7800-a4e3-11ea-99ef-e5f88117a7b8.png)

same result

**Comment by mathieustan** [comment]
@DanielAlcaraz oh ... crap. It ll be fixed tomorow morning

**Comment by mathieustan** [comment]
Should be done. Sorry again ... 🤦 

Release [v0.2.4](https://github.com/mathieustan/vue-datepicker/releases/tag/0.2.4)
