### ISSUE TITLE
Uncaught ReferenceError: BodyScrollLock is not defined

### ISSUE THREAD

**Issue by GMArjun** [mathieustan/vue-datepicker#53]
I Added [https://github.com/mathieustan/vue-datepicker/blob/master/dist/vue-datepicker.min.js](url) to my html file below the  vue script. In console it shows this error (Uncaught ReferenceError: BodyScrollLock is not defined).

**Comment by mathieustan** [comment]
Hmm. I think dependencies aren't downloaded when you only add script. 
You should use classic way, with `npm install` or `yarn add` to install it properly.
