### ISSUE TITLE
Support enterable date (or icon only)

### ISSUE THREAD

**Issue by mikeerickson** [mathieustan/vue-datepicker#61]
I am trying to create an interface whereby users can enter the desired, or if they would like to use datepicker, then they can click a support icon.

I am reviewing props and I don't see ability to use icon ONLY or allow for data entry. I can create a separate `<input v-model="selectedDate">` object to support the entry, but i don't see support for icon only.

**Comment by mathieustan** [comment]
Actually, you can use custom activator. 
At the documentation's end, you can find an example : # Custom activator

**Comment by mikeerickson** [comment]
@mathieustan yes, I did manage to find that example and have implemented a solution that works great for my desired use case.
