### ISSUE TITLE
[Enhancement] RTL style

### ISSUE THREAD

**Issue by raminjafary** [mathieustan/vue-datepicker#66]
There is a few style issues regarding positioning of elements in RTL mode. If you are willing to accept any collaboration let me know.

**Comment by mathieustan** [comment]
@raminjafary Hello :) 

If you want to create a PR, there is no problem about that.
I need to add a contributing guide :)

**Comment by raminjafary** [comment]
@mathieustan Nice :) I'll work on this issue:)

**Comment by mathieustan** [comment]
Hi @raminjafary. Sorry for the delay. 

I'm working on datepicker those days. I'll add your PR.

**Comment by raminjafary** [comment]
I'll keep contributing to it if you please. 
Thanks.
