### ISSUE TITLE
Datepicker order year, month, day

### ISSUE THREAD

**Issue by Webinsane** [mathieustan/vue-datepicker#68]
Hello. First to say great datepicker. You have done a wonderful job. We need to use this datepicker for date of birth input. So, when user initiates datepicker we need to open years selection, when year is chosen user picks the month and on third step they choose the day. Let me know if this is possible. Thanks!

**Comment by mathieustan** [comment]
hello @Webinsane. Thank you :) 

I think it's possible. I'm working on datepicker to make it cleaner. I may add this feature.

**Comment by mathieustan** [comment]
@Webinsane It will be possible soon :)

**Comment by andreasseiler** [comment]
Hi @mathieustan,

thanks from my side too! This is the best DatePicker for vue I know of!! 

Just a quick question about the added feature for starting with the year input. I have the same requirement than @Webinsane. I want the user to start with the Year input and continue with Month and Day. But I can't seem to find an option to make the Picker start with the year. Is it possible?

Thanks and Regards,
Andi

**Comment by mathieustan** [comment]
There is an example in demo page with birthday picker. You can see code.

**Comment by andreasseiler** [comment]
Oh damn ... now I fell quite stupid ... sorry for this unnecessary question. 

Thanks,
Andi
