### ISSUE TITLE
in-range selected on MobileMode is not triggered

### ISSUE THREAD

**Issue by EsilvGuillaume** [mathieustan/vue-datepicker#7]
Hi @mathieustan 

I have a problem with your lib, indeed when i used your Vue-datepicker with mobile mode (with chrome or mozilla) i can't see the range that i select. In desktop mode we have the in-range class, but apparently not in mobile mode. Maybe you can help me with this issue, or it's a missing thing with your development ? 

Nice work man, keep it up

**Comment by mathieustan** [comment]
Hello,

It’s working properly for me. Can you send more details ? Maybe a screenshot ?

**Comment by EsilvGuillaume** [comment]
Hi @mathieustan,

My problem is still here, even with the update rc-7
When i open the datePicker with fullscreenMobile mode on mozilla or chrome mobile, i have this : 
![datePickerMobileMode](https://user-images.githubusercontent.com/7085383/64941480-1d850a00-d867-11e9-92c9-e5cc2683a0d3.PNG)
So there are no problem with that, but if i change the date with 9 september on startDate and place my mouse on 15 september, the rangeClass doesn't appear
![datePickerMobileModeRange](https://user-images.githubusercontent.com/7085383/64941597-6dfc6780-d867-11e9-833e-064b8f02a0f6.PNG)

When i select the new range, if i open again the datePicker i can see the range, this is just a problem during the choice of dateRange

**Comment by mathieustan** [comment]
Hello @EsilvGuillaume,

Ok, it's not a bug. When you are in a mobile view (even if it's desktop mobile view), it acts like in real mobile, and there is no hover (because you can't hover something with your fingers). 

The class appears when you are hovering dates or when you selected a range.
