### ISSUE TITLE
Calendar icon

### ISSUE THREAD

**Issue by cdvrooman** [mathieustan/vue-datepicker#72]
Hello,
  I really like your datepicker! I was wondering if there is any way to specify a different calendar icon? That would allow for better integration with a framework like Vuetify or to use the Bootstrap Vue icons, for example.

  Keep up the great work!

  Sincerely,
    Christopher

**Comment by mathieustan** [comment]
You can use a custom icon slot in v0.2.11. 

Exemple: 

```
<template>
  <VueDatePicker v-model="date">
    <template #input-icon>
      <i class="fa fa-calendar-week" />
    </template>
  </VueDatePicker>
</template>
```
