### ISSUE TITLE
Error on dev

### ISSUE THREAD

**Issue by fingunt** [mathieustan/vue-datepicker#74]
am i try this error what could it be?
![Captura de Tela 2020-11-26 às 16 32 48](https://user-images.githubusercontent.com/33792792/100386937-82a8c380-3005-11eb-85f0-e3a8714a9e78.png)

**Comment by fingunt** [comment]
VueDatePicker(
                      v-model="schedule.start_date",
                      inline,
                      color="#7159c1",
                      locale="locale",
                      @input="selectTimesCommomArea"
                    )
my component

**Comment by mathieustan** [comment]
locale should not be a string. 

Here an example from README : 
```
const locale = {
  lang: {
    name: 'it',
    weekdays: 'domenica_lunedì_martedì_mercoledì_giovedì_venerdì_sabato'.split('_'),
    weekdaysShort: 'dom_lun_mar_mer_gio_ven_sab'.split('_'),
    weekStart: 1,
    months: 'gennaio_febbraio_marzo_aprile_maggio_giugno_luglio_agosto_settembre_ottobre_novembre_dicembre'.split('_'),
    monthsShort: 'gen_feb_mar_apr_mag_giu_lug_ago_set_ott_nov_dic'.split('_'),
    formats: {
      LT: 'HH:mm',
      LTS: 'HH:mm:ss',
      L: 'DD/MM/YYYY',
      LL: 'D MMMM YYYY',
      LLL: 'D MMMM YYYY HH:mm',
      LLLL: 'dddd D MMMM YYYY HH:mm',
    },
    ordinal: n => `${n}º`,
    buttonCancel: 'Annulla',
    buttonValidate: 'Ok',
    rangeHeaderText: 'Dalle %d Alle 13',
  },
};
```

**Comment by fingunt** [comment]
Yes, sorry thanks man
