### ISSUE TITLE
Restrict range to specific number of days

### ISSUE THREAD

**Issue by mrdigitalau** [mathieustan/vue-datepicker#78]
Hi there,

Thanks for your hard work - this is by far the nicest looking and easy to use datepicker I have found.

Just a quick one, would there be a way to restrict a range to a block?

Eg, people can only choose dates in 3 day blocks?

Thanks!

**Comment by mathieustan** [comment]
Hello @mrdigitalau. Thanks :) 

You'll like to set a number of days for range selection ? eg. client can only select X days ? 
Maybe you can disable days when first day has been selected  ?
