### ISSUE TITLE
Proposal: Consider renaming `endDate` to `maxDate` 

### ISSUE THREAD

**Issue by kfirba** [mathieustan/vue-datepicker#8]
Hey again!

There are 2 props that designate a start and end possible dates for the datepicker, but their names aren't matching. I'm talking about the `minDate` and `endDate`. I personally think that if we go with `minDate`, there should be a corresponding `maxDate` instead of `endDate`. We can also argue about having a `startDate` instead of a `minDate`, but I think that `min` and `max` convey more meaning as of what this prop controls.

@mathieustan what do you think?

**Comment by mathieustan** [comment]
Yes I'm aware of this ... I failed when naming those props.
I think min & max are more appropriate.

**Comment by mathieustan** [comment]
Done in V0.1.8
